In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
np.random.seed(43)   #定义随机数生成种子
df = pd.DataFrame({   #创建DataFrame格式的数据
    'color':['black']*5+['white']*5,
    'age':np.random.rand(10)*10,
    'weight':np.random.rand(10)*100,
    'type':['cat']*5+['dog']*5
})

In [3]:
print(df[0:10])

   color       age     weight type
0  black  1.150546  39.495002  cat
1  black  6.090665  80.204712  cat
2  black  1.333910  25.442113  cat
3  black  2.405896   5.688494  cat
4  black  3.271391  86.664864  cat
5  white  8.591375  22.102900  dog
6  white  6.660902  40.498945  dog
7  white  5.411622  31.609647  dog
8  white  0.290138   7.666270  dog
9  white  7.337483  84.322469  dog


In [5]:
df['color'] = pd.get_dummies(df['color'])  #利用pandas调用one-hot编码函数
df['type'] = pd.get_dummies(df['type'])   
print(df[0:10])

   color       age     weight  type
0      0  1.150546  39.495002     0
1      0  6.090665  80.204712     0
2      0  1.333910  25.442113     0
3      0  2.405896   5.688494     0
4      0  3.271391  86.664864     0
5      1  8.591375  22.102900     1
6      1  6.660902  40.498945     1
7      1  5.411622  31.609647     1
8      1  0.290138   7.666270     1
9      1  7.337483  84.322469     1


In [6]:
x = df[['color','age','weight']].values   #训练数据   
y = df[['type']].values   #训练标签

In [7]:
model = keras.Sequential()   #创建Sequential模型
model.add(keras.layers.Dense(50,input_dim = x.shape[1],activation='relu'))   #输入层
model.add(keras.layers.Dense(25,activation='relu'))   #隐藏层
model.add(keras.layers.Dense(y.shape[1],activation='sigmoid'))   #输出层

In [8]:
model.summary()   #查看模型概况

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                200       
_________________________________________________________________
dense_1 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 26        
Total params: 1,501
Trainable params: 1,501
Non-trainable params: 0
_________________________________________________________________


In [9]:
model = keras.Sequential([
    keras.layers.Dense(50,input_dim = x.shape[1],activation='relu'),
    keras.layers.Dense(25,activation='relu'),
    keras.layers.Dense(y.shape[1],activation='sigmoid')
])

In [10]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                200       
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 26        
Total params: 1,501
Trainable params: 1,501
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss='binary_crossentropy',optimizer='SGD')   #配置训练参数

In [12]:
model.fit(x,y,epochs=500)   #模型训练

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 1.3260
Epoch 2/500
1/1 [==============================] - 0s 6ms/step - loss: 4.0140
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 1.0345
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 2.7099
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 1.6669
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 2.8049
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7414
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 1.2713
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 1.5858
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 0.8598
Epoch 11/500
1/1 [==============================] - 0s 3ms/step - loss: 1.0892
Epoch 12/500
1/1 [==============================] - 0s 4ms/step - loss: 0.9322
Epoch 13/500
1/1 [==============================] - 0s 3ms/ste

In [13]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [14]:
model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 0.4093
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3585
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3312
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3273
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3388
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3478
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3460
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3370
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3269
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3213
Epoch 11/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3195
Epoch 12/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3204
Epoch 13/500
1/1 [==============================] - 0s 5ms/ste

In [15]:
x_test =  pd.DataFrame({   #单个测试数据
    'color':['black'],
    'age':np.random.rand(1)*10,
    'weight':np.random.rand(1)*100,
})
x_test['color'] = pd.get_dummies(['color'])   #对color属性进行one-hot编码
print(x_test)

   color       age     weight
0      1  8.489391  97.146509


In [16]:
model.predict(x_test.values)   #模型预测

array([[0.9986272]], dtype=float32)

In [17]:
df = pd.DataFrame({
    'color':['black']*5+['white']*5,
    'age':np.random.rand(10)*10,
    'weight':np.random.rand(10)*100,
    'sleep_time':np.random.rand(10)*24,
})

In [18]:
print(df[0:10])

   color       age     weight  sleep_time
0  black  3.853769  47.559637   20.760411
1  black  9.544881  63.637368   16.132255
2  black  4.457584  97.820413   15.090859
3  black  6.697247  90.866276    6.613411
4  black  0.825000  91.015308   21.521934
5  white  8.970986  52.525567    4.965393
6  white  2.980035  10.401895    9.705726
7  white  2.623048  18.091460   23.845740
8  white  0.051295  95.304022   17.657450
9  white  5.432025  41.195298   10.681474


In [19]:
df['color'] = pd.get_dummies(df['color'])

In [20]:
x = df[['color','age','weight']].values   #训练数据
y = df[['sleep_time']].values   #训练标签

In [21]:
model = keras.Sequential()
model.add(keras.layers.Dense(50,input_dim = x.shape[1],activation='relu'))
model.add(keras.layers.Dense(25,activation='relu'))
model.add(keras.layers.Dense(1))

In [22]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 50)                200       
_________________________________________________________________
dense_7 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 26        
Total params: 1,501
Trainable params: 1,501
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.compile(loss='mean_squared_error',optimizer='Adam')

In [24]:
model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 534ms/step - loss: 243.8687
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 225.2032
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 207.8593
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 192.0794
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 177.4221
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 163.8324
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 151.3135
Epoch 8/500
1/1 [==============================] - 0s 3ms/step - loss: 139.8751
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 129.5034
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 120.1930
Epoch 11/500
1/1 [==============================] - 0s 4ms/step - loss: 111.9354
Epoch 12/500
1/1 [==============================] - 0s 4ms/step - loss: 104.7149
Epoch 13/500
1/1 [=================

In [27]:
x_test =  pd.DataFrame({
    'color':['black'],
    'age':np.random.rand(1)*10,
    'weight':np.random.rand(1)*100,
})
x_test['color'] = pd.get_dummies(['color'])
model.predict(x_test.values)   #模型预测


array([[14.07941]], dtype=float32)

In [28]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [29]:
np.random.seed(43)
df = pd.DataFrame({   #虚拟数据集
    'color':['black']*5+['white']*5,
    'age':np.random.rand(10)*10,
    'weight':np.random.rand(10)*100,
    'type':['cat']*5+['dog']*5
})
df['color'] = pd.get_dummies(df['color'])   #对color属性进行one-hot编码
df['type'] = pd.get_dummies(df['type'])   #对type属性进行one-hot编码
x = df[['color','age','weight']].values   #训练数据
y = df[['type']].values   #训练标签

In [30]:
class myModel(keras.Model):   #子类API定义神经网络
    def __init__(self,x,y):
        super(myModel,self).__init__()
        self.d1 = keras.layers.Dense(50,input_dim = x.shape[1],activation='relu')   #输入层
        self.d2 = keras.layers.Dense(25,activation='relu')   #隐藏层
        self.d3 = keras.layers.Dense(y.shape[1],activation='sigmoid')   #输出层
    def call(self,x):   #前向传播
        x = self.d1(x)
        x = self.d2(x)
        output = self.d3(x)
        return output

In [31]:
model = myModel(x,y)

In [32]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [33]:
model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 832ms/step - loss: 0.6161
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6066
Epoch 3/500
1/1 [==============================] - 0s 10ms/step - loss: 0.5976
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 0.5914
Epoch 5/500
1/1 [==============================] - 0s 11ms/step - loss: 0.5834
Epoch 6/500
1/1 [==============================] - 0s 11ms/step - loss: 0.5789
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 0.5726
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5661
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5614
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.5559
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5499
Epoch 12/500
1/1 [==============================] - 0s 4ms/step - loss: 0.5450
Epoch 13/500
1/1 [==============================] - 0s 

In [34]:
x_test =  pd.DataFrame({   #单个测试数据
    'color':['black'],
    'age':np.random.rand(1)*10,
    'weight':np.random.rand(1)*100,
})
x_test['color'] = pd.get_dummies(['color'])
model.predict(x_test.values)   #模型预测

array([[0.94634175]], dtype=float32)