In [1]:
import tensorflow as tf

In [2]:
x = tf.random.normal([1,4,4,1])   #构建批大小、图像尺寸、输入通道数分别为1，4x4和1的图像
w = tf.random.normal([4,4,1,3])   #构建卷积核大小、输入及输出通道数分别为4x4、1和3的卷积核
out = tf.nn.conv2d(x,w,strides=(1,1,1,1),padding='SAME')   #步长为1，自动进行补0
print(out)

tf.Tensor(
[[[[ 0.75354624  2.9657838   2.4456027 ]
   [ 1.4235408  -0.57771707 -0.86387396]
   [ 0.12562671 -1.0006247   0.8186578 ]
   [ 0.09569051 -1.5308489  -1.1079049 ]]

  [[-0.48999617  4.5939465   1.3215225 ]
   [ 1.9373882   6.2975674   3.869739  ]
   [ 0.2415908   4.433558   -0.26597685]
   [ 0.27684122 -2.0135245  -0.22128999]]

  [[-1.0539551   0.5599128   1.8140148 ]
   [-2.4591622  -6.288887   -2.5512826 ]
   [ 0.818917   -0.16794622  0.63845235]
   [ 0.92871296  2.5773816   0.8756951 ]]

  [[-0.11072803  0.71853524 -0.5985398 ]
   [ 1.1795458   2.3308244   1.5516977 ]
   [ 0.5331741   3.6385615   0.7910669 ]
   [-0.5286833  -2.617179   -1.9543285 ]]]], shape=(1, 4, 4, 3), dtype=float32)


In [3]:
x = tf.random.normal([1,4,4,1])   
out = tf.nn.max_pool(x,ksize=[1,2,2,1],strides=2,padding='VALID')   #步长为2，不进行补0
print(out)

tf.Tensor(
[[[[1.3880711 ]
   [0.61120605]]

  [[1.6649961 ]
   [0.41247115]]]], shape=(1, 2, 2, 1), dtype=float32)


In [4]:
x = tf.random.normal([1,4,4,1])   #构造图像结构
layer = tf.keras.layers.Conv2D(filters=3,kernel_size=4,strides=1,padding='SAME')   #调用卷积层类
out = layer(x)
print(out.shape)
layer = tf.keras.layers.MaxPooling2D(pool_size=2,strides=2,padding='SAME')   #调用最大池化层类
out = layer(x)
print(out.shape)
layer = tf.keras.layers.AveragePooling2D(pool_size=2,strides=2,padding='SAME')   #调用平均池化层类
print(out.shape)

(1, 4, 4, 3)
(1, 2, 2, 1)
(1, 2, 2, 1)
