In [ ]:
!conda install -n tensorflow2 ipykernel --update-deps --force-reinstall
import tensorflow as tf

: 

In [4]:
scalar_int = tf.constant(2)   #创建整型标量张量
scalar_float = tf.constant(3.14)   #创建浮点型标量张量
scalar_string = tf.constant('hello')   #创建字符串型标量张量
print(scalar_int)
print(scalar_float)
print(scalar_string)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3.14, shape=(), dtype=float32)
tf.Tensor(b'hello', shape=(), dtype=string)


In [5]:
vector_int = tf.constant([2])   #创建整型向量张量
vector_float = tf.constant([3.0,4.0])   #创建浮点型向量张量
vector_string = tf.constant(['hello','world'])   #创建字符串型向量张量
print(vector_int)
print(vector_float)
print(vector_string)

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([3. 4.], shape=(2,), dtype=float32)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [6]:
matrix_int = tf.constant([[1],[2]])   #创建整型矩阵张量
matrix_float = tf.constant([[3.0],[4.0]])   #创建浮点型矩阵张量
matrix_string = tf.constant([['hello'],['world']])   #创建字符串型矩阵张量
print(matrix_int)
print(matrix_float)
print(matrix_string)

tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[3.]
 [4.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[b'hello']
 [b'world']], shape=(2, 1), dtype=string)


In [7]:
scalar_int = tf.constant(1)
vector_int = tf.constant([1,2])
matrix_int = tf.constant([[1],[2],[3]])
print(tf.rank(scalar_int))
print(tf.rank(vector_int))
print(tf.rank(matrix_int))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [8]:
import numpy as np

In [9]:
list = [1,2,3]   #创建python列表
array = np.array([1.0,2.0,3.0])   #创建numpy数组
print(tf.convert_to_tensor(list))   #将列表转换为tensor
print(tf.convert_to_tensor(array))   #将numpy数组转换为tensor

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [10]:
list = [1,2,3]
array = np.array([1.0,2.0,3.0])
print(tf.convert_to_tensor(list,dtype=tf.int64))    
print(tf.convert_to_tensor(array,dtype=tf.float64))

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)


In [18]:
print(tf.zeros((3,3)))   #创建3x3的全0矩阵
print(tf.ones((3,3)))   #创建3x3的全1矩阵

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [20]:
print(tf.zeros((3,3),dtype=tf.int32))
print(tf.ones((3,3),dtype=tf.int64))	

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int64)


In [21]:
print(tf.fill((3,3),value=5)) 

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [22]:
print(tf.random.normal((3,3),2,4))   #创建正态分布张量

tf.Tensor(
[[ 0.46796322  0.4245894  -3.4520144 ]
 [ 0.2141273   0.61317873  2.6008067 ]
 [ 3.7181065   4.0746784   1.9352145 ]], shape=(3, 3), dtype=float32)


In [23]:
print(tf.random.uniform((3,3),0,10))   #创建均匀分布张量

tf.Tensor(
[[0.5259907 5.6985354 4.4980264]
 [2.5474274 0.6768787 2.1822   ]
 [2.931416  8.758934  2.7595413]], shape=(3, 3), dtype=float32)


In [25]:
print(tf.add(2,3))   #加法
print(tf.subtract(2,3))   #减法
print(tf.multiply(2,3))   #乘法
print(tf.divide(2,3))   #除法

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


In [26]:
a = tf.constant(2)
b = tf.constant(3)
print(a+b)   #加法
print(a-b)   #减法
print(a*b)   #乘法
print(a/b)   #除法

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


In [27]:
print(tf.abs(-2))    #求绝对值
print(tf.pow(2,2))   #求次方
float_number = tf.cast(4,tf.float32)   #强制转换类型
print(tf.sqrt(float_number))   #开平方

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [30]:
a = tf.random.normal([5,6])   #创建5x6正态分布张量
b = tf.random.normal([6,5])   #创建6x5正态分布张量
print(tf.matmul(a,b))   #矩阵相乘

tf.Tensor(
[[ 4.8489485  -3.836883   -0.27460623 -3.5942094   0.42221028]
 [ 1.1547904  -4.090041    1.5693511  -0.37471485 -0.48131537]
 [-0.3619895   0.1380136  -3.641617    0.20442271 -0.28251648]
 [ 2.3332467   1.1007496   4.9263606  -1.1039075  -1.1128942 ]
 [-1.9001296  -0.34121484 -4.2496653   0.52446157 -1.5932306 ]], shape=(5, 5), dtype=float32)


In [31]:
print(a@b)   #矩阵相乘

tf.Tensor(
[[ 4.8489485  -3.836883   -0.27460623 -3.5942094   0.42221028]
 [ 1.1547904  -4.090041    1.5693511  -0.37471485 -0.48131537]
 [-0.3619895   0.1380136  -3.641617    0.20442271 -0.28251648]
 [ 2.3332467   1.1007496   4.9263606  -1.1039075  -1.1128942 ]
 [-1.9001296  -0.34121484 -4.2496653   0.52446157 -1.5932306 ]], shape=(5, 5), dtype=float32)


In [32]:
a = tf.random.uniform((5,5),2,10) 
print(a)

tf.Tensor(
[[5.4449844 8.384746  2.1526718 3.279498  4.229474 ]
 [2.9552727 6.896822  2.8514347 8.140891  5.203436 ]
 [3.5175123 6.409215  9.754162  7.5541754 3.521409 ]
 [9.186459  4.523484  3.1946993 8.142016  4.0146027]
 [9.412505  4.466488  3.3088903 8.501272  6.197157 ]], shape=(5, 5), dtype=float32)


In [33]:
print(a[1])   #索引第二行

tf.Tensor([2.9552727 6.896822  2.8514347 8.140891  5.203436 ], shape=(5,), dtype=float32)


In [34]:
print(a[2][2])   #索引第三行第三列的值

tf.Tensor(9.754162, shape=(), dtype=float32)


In [39]:
print(a[2,0:2])   #索引第三行前2列的值

tf.Tensor([3.5175123 6.409215 ], shape=(2,), dtype=float32)


In [40]:
a = tf.random.normal((3,4))
print(a)

tf.Tensor(
[[ 0.22210361 -1.554137   -1.1776102   0.8784127 ]
 [ 1.3135794  -0.39600548  1.4259037   0.8974065 ]
 [-0.22344843  1.3599309   0.58194727  0.39072707]], shape=(3, 4), dtype=float32)


In [41]:
print(tf.reshape(a,(2,6)))   #维度转换

tf.Tensor(
[[ 0.22210361 -1.554137   -1.1776102   0.8784127   1.3135794  -0.39600548]
 [ 1.4259037   0.8974065  -0.22344843  1.3599309   0.58194727  0.39072707]], shape=(2, 6), dtype=float32)


In [42]:
print(tf.reshape(a,(2,-1)))

tf.Tensor(
[[ 0.22210361 -1.554137   -1.1776102   0.8784127   1.3135794  -0.39600548]
 [ 1.4259037   0.8974065  -0.22344843  1.3599309   0.58194727  0.39072707]], shape=(2, 6), dtype=float32)


In [43]:
a = tf.random.normal((28,28))
a = tf.expand_dims(a,axis=0)   #增添第一维
a = tf.expand_dims(a,axis=3)   #增添第四维
print(a)

tf.Tensor(
[[[[-1.02202415e+00]
   [ 2.77254224e-01]
   [ 8.62557352e-01]
   [ 9.90465760e-01]
   [-1.32723784e+00]
   [ 6.34071529e-01]
   [ 5.12828112e-01]
   [ 1.11263549e+00]
   [-7.01488614e-01]
   [-6.04666889e-01]
   [ 1.50991094e+00]
   [ 1.84574321e-01]
   [ 1.78074911e-02]
   [ 2.37986565e-01]
   [-3.57144892e-01]
   [-8.51860762e-01]
   [ 3.83013695e-01]
   [ 3.23607326e-01]
   [-6.70833707e-01]
   [ 2.02322721e+00]
   [ 9.02828097e-01]
   [ 1.42376935e+00]
   [-4.81191993e-01]
   [-1.05549252e+00]
   [ 3.05102706e-01]
   [-6.26974225e-01]
   [-5.71669638e-01]
   [-4.60515529e-01]]

  [[-6.57740772e-01]
   [ 2.51900107e-01]
   [ 1.83169496e+00]
   [ 5.35394907e-01]
   [ 1.23439682e+00]
   [ 2.11978272e-01]
   [ 3.43240619e-01]
   [ 1.59037411e+00]
   [ 7.28585720e-01]
   [ 1.53866661e+00]
   [ 1.99841991e-01]
   [ 5.23786724e-01]
   [-3.34164202e-01]
   [ 9.64533463e-02]
   [ 4.34561849e-01]
   [ 3.20231393e-02]
   [-2.53670633e-01]
   [-4.41315472e-02]
   [-3.13817406e+00]


In [44]:
a = tf.random.normal((1,28,28,1))
a = tf.squeeze(a,axis=0)   #删除第一个维度
a = tf.squeeze(a,axis=2)   #删除最后一个维度
print(a)

tf.Tensor(
[[-4.89325970e-01  1.21939969e+00  4.19008315e-01 -2.48495579e+00
  -9.67439473e-01 -4.85590905e-01  3.18354577e-01 -9.75308716e-02
  -2.27310562e+00  6.38908923e-01  2.23114014e+00  2.22795391e+00
   1.28005311e-01 -5.84694326e-01 -8.67854595e-01  1.41559407e-01
  -9.70309436e-01 -6.31816387e-01 -8.19874227e-01 -9.19832468e-01
  -2.12479496e+00 -3.77473593e-01  8.70875299e-01  1.03720832e+00
  -4.54606526e-02 -1.53157043e+00  1.45208228e+00 -8.26113820e-01]
 [-1.52085149e+00 -1.39239562e+00 -1.89369345e+00  1.02270913e+00
  -5.99031270e-01 -5.26223779e-01 -2.17381150e-01 -6.20335698e-01
  -3.99413049e-01 -2.69471765e-01  1.51681519e+00 -1.87938318e-01
   9.95966136e-01  5.55674255e-01  7.26301432e-01  5.73700130e-01
   8.77953395e-02  1.70995963e+00 -6.58836484e-01 -8.72981906e-01
   5.53405166e-01  8.53602767e-01  6.36636794e-01  7.92279959e-01
  -2.21860743e+00 -8.88067961e-01  5.45033440e-02 -2.53454804e-01]
 [-4.88521427e-01  7.64077306e-01  2.01407671e+00  1.12418807e+

In [45]:
a = tf.random.normal((1,1,28,28))
a = tf.transpose(a,[0,2,3,1])   #维度交换
print(a)

tf.Tensor(
[[[[-1.23525977e-01]
   [-2.03960657e+00]
   [-4.69323218e-01]
   [ 6.08395338e-01]
   [-1.27368629e+00]
   [-2.95583814e-01]
   [ 1.24512970e+00]
   [-4.20692831e-01]
   [ 3.01660240e-01]
   [ 1.59371272e-01]
   [-2.83713967e-01]
   [-1.14094034e-01]
   [-8.53173554e-01]
   [ 1.04447520e+00]
   [ 1.40974820e-01]
   [ 2.69544661e-01]
   [-1.06915057e+00]
   [-1.01263583e+00]
   [-7.63502479e-01]
   [-1.10095692e+00]
   [-1.10892391e+00]
   [ 1.89461732e+00]
   [ 2.60399175e+00]
   [ 8.53459537e-02]
   [-8.16962242e-01]
   [-1.38651943e+00]
   [-1.04568803e+00]
   [-5.80159783e-01]]

  [[ 8.73292267e-01]
   [ 1.11637712e+00]
   [ 2.29579732e-01]
   [ 1.55509925e+00]
   [ 1.42626858e+00]
   [ 2.67723417e+00]
   [ 2.20907614e-01]
   [-1.22375214e+00]
   [-1.21346366e+00]
   [ 2.56611884e-01]
   [-1.30303836e+00]
   [-8.71690512e-01]
   [ 2.46494031e+00]
   [-1.11467183e-01]
   [-6.29578531e-01]
   [ 5.52053332e-01]
   [-7.09468186e-01]
   [ 5.08989990e-01]
   [-1.48349512e+00]


In [46]:
a = tf.constant(6)
b = tf.constant(6.0)
print(tf.strings.as_string(a))   #整型张量转换为字符串
print(tf.strings.as_string(b))   #浮点型张量转换为字符串

tf.Tensor(b'6', shape=(), dtype=string)
tf.Tensor(b'6.000000', shape=(), dtype=string)


In [47]:
b = tf.constant(6.0)
print(tf.strings.as_string(b,precision=1))   #设置1位小数精度

tf.Tensor(b'6.0', shape=(), dtype=string)


In [48]:
a = tf.constant(['hello'])
print(tf.strings.bytes_split(a))   #字符串分割	

<tf.RaggedTensor [[b'h', b'e', b'l', b'l', b'o']]>


In [49]:
a = tf.constant(['h','e','l','l','o'])
print(tf.strings.join(a))   #字符拼接

tf.Tensor(b'hello', shape=(), dtype=string)


In [50]:
a = tf.constant("ABCD")
print(tf.strings.lower(a))   #小写转换

tf.Tensor(b'abcd', shape=(), dtype=string)


In [51]:
a = tf.constant("abcd")
print(tf.strings.upper(a))   #大写转换

tf.Tensor(b'ABCD', shape=(), dtype=string)


In [52]:
a = tf.ragged.constant([[1,2,3],[],[4,5,6]])   #创建整型Ragged张量
b = tf.ragged.constant([['hello'],[],['world']])   #创建字符串型Ragged张量
print(a)
print(b)

<tf.RaggedTensor [[1, 2, 3], [], [4, 5, 6]]>
<tf.RaggedTensor [[b'hello'], [], [b'world']]>


In [53]:
c = tf.ragged.constant([[1,2,3],[],['hello']])

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [54]:
print(a[0])
print(b[2])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([b'world'], shape=(1,), dtype=string)


In [55]:
a = tf.ragged.constant([[1,2,3],[],[4,5,6]])
print(a+2)
print(a-2)
print(a*2)
print(a/2)

<tf.RaggedTensor [[3, 4, 5], [], [6, 7, 8]]>
<tf.RaggedTensor [[-1, 0, 1], [], [2, 3, 4]]>
<tf.RaggedTensor [[2, 4, 6], [], [8, 10, 12]]>
<tf.RaggedTensor [[0.5, 1.0, 1.5], [], [2.0, 2.5, 3.0]]>


In [56]:
a = tf.ragged.constant([[1,2,3],[],[4,5,6]])
rule = lambda x: x * 3 + 1
print(tf.ragged.map_flat_values(rule,a))   #函数映射变换

<tf.RaggedTensor [[4, 7, 10], [], [13, 16, 19]]>
